- mkdocs.yml
This MR:
- Adds a link to this repository at the documentation.
The link looks like this
We might want to discuss the text (currently "flowcean/flowcean") and the icon. For a list of possible choices have a look here https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon.
Closes #46.
> Add github link to documentation

- .github/workflows/ci.yml
- README.md
Adds some more badges. Integrating a code coverage badges is much more complicate than in GitLab... We have to use third-party services for such information and badge. I'll propose to skip that for now.
Closes #45
> Add some more Badges

- examples/automatic_lashing_platform/.gitignore
- examples/automatic_lashing_platform/data.dvc
This PR:
- Remvoes the old ALP data from DVC
- Add a new batch of simulation data from the ALP to the DVC (~16.000 simulation runs)
> Add new ALP sim data

- pyproject.toml
This PR:
- Constrains the numpy version to pre-2.0 versions for now
Closes #105.
> Constrain numpy for now

- .github/workflows/ci.yml
This MR:
- Adds the one tank example to the ci runs.
This example uses both scikit-learn and pytorch/lightning, so runtime in the pipeline might be an issue? However, since it does not rely on dvc, the results might be more consistent and we could use it as a subsitutaion for failure time prediction?
> Add one tank example to ci/cd runs

- src/flowcean/transforms/rechunk.py
- tests/transforms/test_rechunk.py
This PR:
- Adds a `Rechunk` transform. Even though this transform is a really slim wrapper around `df.rechunk()` however I still think it's worth to create a dedicated transform for this so we have the functionality documented for cps developers.
Closes #108.
> Add rechunk transform

- src/flowcean/transforms/sliding_window.py
`groupby_rolling` is deprecated and is now called `rolling`
> `groupby_rolling` -> `rolling`

- src/flowcean/transforms/__init__.py
- src/flowcean/transforms/resample.py
- tests/transforms/test_resample.py
This PR:
- Adds a new implementation of a `Resample` transform to change the sampling rate of time series features.
Probably superseeds #23 as this uses the new time series format.
The implementation could possible still be improved quite a bit. As I use interpolation methods from scipy there is probably no way around moving the data from polars to python and back. @schmidma maybe you have another clever idea how to optimize it further / make it more polars.
> Add Resample transform

- src/flowcean/core/environment/offline.py
- tests/core/test_to_time_series.py
This PR:
- Adds a `to_time_series` method to `OfflineEnvironment` to convert one to a single entry in a time series envrionment.
For now this method is directly attached to the `OfflineEnvironment`. This however adds "production" code to the base class. We can / should discuss if and where we could move such a method instead.
> Add `to_time_series` method

- src/flowcean/transforms/resample.py
This PR:
- Replaces the type of `interpolation_method` in the `ResampleTransform` with a type alias. This provides the user with better editor suggestions and type checking.
> Replace str interpolation_method with type alias

- examples/automatic_lashing_platform/.gitignore
- examples/automatic_lashing_platform/real_data.dvc
This PR:
- Adds a first batch of real meassurement data from the ALP. The data *should* have the same format then the simulation data but is limited to six second recordings.
We shall discuss if this data remains in the repo when / if the storage becomes public.
> Add real ALP meassurement data

- src/flowcean/core/transform.py
- tests/transforms/test_rechunk.py
This PR:
- Make transform directly callable. This simply acts as a wrapper around the `transform` so no changes to existing transforms are required.
Closes #142.
> Make transforms callable

- examples/automatic_lashing_platform/.gitignore
- examples/automatic_lashing_platform/alp_real_data.parquet.dvc
- examples/automatic_lashing_platform/alp_sim_data.parquet.dvc
- examples/automatic_lashing_platform/data.dvc
- examples/automatic_lashing_platform/preload_alp_data.py
- examples/automatic_lashing_platform/real_data.dvc
- examples/automatic_lashing_platform/run.py
This PR:
- Repacks the ALP data into single `parquet` files and adjust the example accordingly. This makes working with the data much easier. The helper script to convert the original alp data into a single file is included as well.
> Pack ALP data into single files

- src/flowcean/core/environment/offline.py
This PR:
- Adds a `write_parquet` to the offline environment. This allows the user to store data after loading / transforming it and can save time when making changes to the learners / metrics without changing the loading part. Does also support the time series representation.
This is "just" a wrapper around polars functionality - however I would argue that it's easier for a user to have a "flowcean-method" then having to dive into the polars docs. Also this makes sure the writing shows up in our documentation. If you need more options you can still use them by directly using the data frame.
> Add `write_parquet` method to offline environment

- pyproject.toml
This PR:
- Does what the title says. Polars since version `1.12` has the bugfix for list `evals`.
> Unpin polars and limit version to latest one with the bugfix

- docs/user_guide/environment.md
- docs/user_guide/experiment.md
- docs/user_guide/learning_strategies.md
- docs/user_guide/model.md
- docs/user_guide/modules.md
- pyproject.toml
This PR:
- Replaces the old `www3.tuhh.de` domain with `flowcean.me` in documentation links.
Closes #169.
> Replace www3.tuhh.de with flowcean.me domain in links

- pyproject.toml
- uv.lock
I created a release for `v0.2.0`, so our latest main should be `0.3.0` to avoid conflicts confusion
> bump version to 0.3.0

- examples/active_learning/run.py
- examples/boiler/run.py
- examples/coffee_machine/run.py
- examples/failure_time_prediction/run.py
- examples/linear_data/run.py
- examples/one_tank/run.py
- examples/ros_offline/run.py
- justfile
- pyproject.toml
- uv.lock
Currently, flowcean is installed from official released sources (pypi) when scripts are run with `uv`.
This PR adds a section telling `uv` to use flowcean from the local path instead.
> Add flowcean as editable dependency to scripts

- src/flowcean/environments/datasetprediction.py
Resolves #191 
The PR implements a mock environment for prediction. The environment is mainly a wrapper for the `Dataset` environment which prints the prediction result to the console.
Open Questions for Review:
- The environment's ´observe` and `step` functions are nearly equivalent to the `Streaming`-environment. Should we derive the `DatasetPredictionEnvironment` from the ´Streaming`-environment (and `Actable`environment) instead to avoid duplicated code? In this case, the environment doesn't wrap a `Dataset`environment, but a general `OfflineEnvironment`.
- There are no tests for this environment. I am not sure whether there exist useful test cases.
> Add Prediction Environment

- .github/workflows/release.yml
Adapt pre-release check according to https://peps.python.org/pep-0440/
Treating pre-releases and development releases as pre-releases on github
> Adapt pre-release check according to PEP440

- pyproject.toml
- uv.lock
Eventually, the dev-dependencies field will be deprecated and removed.
https://docs.astral.sh/uv/concepts/projects/dependencies/#legacy-dev-dependencies
> Migrate to dev dependency groups

- examples/active_learning/run.py
- src/flowcean/core/model.py
- src/flowcean/learners/dummy_learner.py
- src/flowcean/learners/grpc/learner.py
- src/flowcean/models/pytorch.py
- src/flowcean/models/sklearn.py
- src/flowcean/strategies/incremental.py
- src/flowcean/strategies/offline.py
- tests/models/save_load.py
This PR:
- Adds code to load and save all existing models
- Adds code to load and save models with transforms, rapping arbitrary model types
ToDos:
This PR relies heavily on `pickle` and untyped dict access. It's not nice, but it works for now!
The only downside is: We cannot save `Lambda` transforms with this approach, because lambda functions aren't supported by `pickle` alone. However we could use `dill` a `pickle` extension which supports nearly everything python has to offer. Any feelings about this?
> Add Model saving and loading

- justfile
- pyproject.toml
- uv.lock
This PR:
- Moves example only dependencies into own group.
- Adjust the `justfile' to use the new group where necessary.
If you want to install the packages required by the examples as well, you can run `uv sync --group examples` or use `uv run --directory ./examples/<ExampleName> run.py` to automaticlly install dependencies for this run.
> Move example dependencies into own group

- src/flowcean/polars/transforms/median.py
- tests/polars/transforms/test_mean.py
- tests/polars/transforms/test_median.py
This PR:
- Adds a `replace` flag to the `Median` transform.
- Adjust the tests for `Median` and `Mean` transform to test for feature replacements.
> Replace flag for Median transform

- src/flowcean/polars/transforms/cast.py
- tests/polars/transforms/test_cast.py
This PR:
- Allows the `Cast` transform to take a dictionary argument of feature-name and target type to apply different casts to different features.
- Add a docstring to the transform.
> Cast dictionary argument

- uv.lock
This PR:
- Update the `uv.lock` dependencies to their latest versions. This is especially useful for `polars`, as the new versions offer better performance, and `torch`, as the current locked version has problems on Windows machines, but it doesn't hurt any of the other dependencies either.
> Update locked dependencies

- src/flowcean/polars/is_time_series.py
- src/flowcean/polars/transforms/__init__.py
- src/flowcean/polars/transforms/sliding_window_ts.py
- tests/polars/transforms/test_sliding_window_ts.py
This PR:
- Adds a `TimeSeriesSlidingWindow` transform. This transform is not very efficient, but I think we would rather have an inefficient transform than none at all. But as I'm using `map_batches` this should be compatible with the streaming engine and does not require all data to be present in memory at the same time.
The transform could still use an example. I'll add one, once we agree on the generel functionality.
> Add Sliding Window for Timeseries

- examples/automatic_lashing_platform/preload_alp_data.py
- pyproject.toml
- src/flowcean/core/strategies/active.py
- src/flowcean/polars/environments/datasetprediction.py
- src/flowcean/polars/environments/streaming.py
- src/flowcean/polars/environments/train_test_split.py
- src/flowcean/polars/transforms/flatten.py
- src/flowcean/polars/transforms/one_cold.py
- src/flowcean/polars/transforms/one_hot.py
- src/flowcean/polars/transforms/standardize.py
- src/flowcean/sklearn/metrics/classification.py
- src/flowcean/sklearn/metrics/regression.py
- uv.lock
This PR:
- Increases the minimum `polars` version to `1.25` to use the new streaming engine.
- Change all `LazyFrame.collect` to use the new `engine` parameter.
Supersedes #251.
> Use new Polars Streaming Engine

- pyproject.toml
- src/flowcean/core/transform.py
- tests/polars/transforms/test_cast.py
- tests/polars/transforms/test_select.py
- uv.lock
This PR:
- Adds a mechanism to compute a hash from arbitrary transforms.
- Adds `cloudpickle` as a dependency for pickle lambdas.
- Adds two tests for hashing. If this PR get's merged we might want to extend the test suite.
This PR is intended to be a "catch-all" with no extra work for transform developers. However, this leads to extreme sensitivity about the order of arguments, even if the order doesn't matter. It should keep this:
- If two hashes are the same, the transforms behave the same
- If two hashes are *not* the same, the transforms _might_ behave differently - but we cannot be sure.
> Add generic Transform hashing

- src/flowcean/core/model.py
This PR:
- Changes the `Model` `Save` and `Load` method to accept a string path.
Closes #263.
> Allow path string in model save or load

- ruff.toml
This PR:
- Removes two rules which were previously ignored but are now removed from `ruff` entirley - so ignoring them no longer has any effect.
> Removed rules removed from ruff

- examples/one_tank/run.py
- src/flowcean/torch/lightning_learner.py
This PR:
- Exposes the `activation_function` as an optional parameter when training an MLP.
> Expose activation function as argument for MLPs

- src/flowcean/polars/transforms/resample.py
- src/flowcean/polars/transforms/signal_filter.py
- tests/polars/transforms/test_signal_filter.py
This PR replaces all `pl.first` in `pl.list.eval` with `pl.element`. The former is outdated and raises and error with the latest polars version.
> Fix Polars List Eval

- src/flowcean/grpc/learner.py
- src/flowcean/sklearn/regression_tree.py
- src/flowcean/torch/lightning_learner.py
- src/flowcean/torch/linear_regression.py
This MR:
- Replaces some `collect` calls with `pl.collect_all`. The later allows polars to apply optimizations to the whole query and reuse cached results. Those changes could potentially speed up learning by a good amount.
> Use `collect_all` instead of two separate collects

- src/flowcean/adapter/opc/adapter.py
This PR:
- Fixes the pre-recording in the OPC Adapter. With the previous implementation the adapter briefly switched back to "pre-recording" after recording was done, dropping all values beside the last two seconds.
- Reduces the log level of the opc-ua library.
> Fix OPC Adapter Pre-Recording

- src/flowcean/adapter/opc/adapter.py
> Add Support for UInt Datatypes in OPC Adapter
