.github/workflows/pages.yml, .github/workflows/pull_request.yml, .gitignore
This hopefully deploys the documentation to GitHub pages
=> upload pages artifact

docs/getting_started/installation.md, src/flowcean/transforms/__init__.py, src/flowcean/transforms/match_sampling_rate.py, tests/transforms/test_match_sampling_rate.py
=> Match sampling rate

LICENSE.txt
Adds a 3-Clause BSD License to our repository
=> Add 3-Clause BSD License

CODING_GUIDELINES.md, docs/examples/one_tank.md, docs/getting_started/new_project.md, docs/user_guide/learning_strategies.md, docs/user_guide/modules.md, docs/user_guide/transform.md, src/flowcean/environments/csv.py, src/flowcean/environments/ode_environment.py, tests/data/test_ode_environment.py
=> Fix Some Misspellings

.github/workflows/ci.yml, docs/examples/one_tank.md, src/flowcean/transforms/match_sampling_rate.py
what it says, while fixing the respective warnings that occur in `main`
=> Fail on warnings in docs build

docs/agenc/index.md, docs/agenc/tuhh.md, mkdocs.yml
Adds basic structure for the documentation and explanation of our research project "AGenC"
=> Add Research Project to Documentation

.github/workflows/ci.yml, pyproject.toml
Adjust the CI yaml to use the newest `hatch` features, like `hatch test` or the hatch github action (https://github.com/pypa/hatch/tree/install)
=> Hatch Action

examples/ros_offline/.gitignore, examples/ros_offline/example_rosbag.dvc, examples/ros_offline/run.py, pyproject.toml, src/flowcean/environments/rosbag.py
Adds a minimal example with ROS data from a single rosbag. This is a first step to supporting time series data. Transforms and further convenience methods will be added in coming PRs.
=> Add RosLoader to load offline data from rosbags

CODE_OF_CONDUCT.md
This minor update of the code of conduct captures a previous discussion on the review process.
=> Details for Coding Guidelines

src/flowcean/core/environment/__init__.py, src/flowcean/core/environment/offline.py, src/flowcean/core/environment/stack.py, tests/core/test_stack.py
This PR:
- Add a new `StackEnvironment` to combine two (or more) `OfflineEnviroments` vertically
- Add helper methods and syntactic sugar to the `OfflineEnvironment`
- Add tests for the new environment
=> Add StackEnvironment

docs/agenc/cml.md, docs/agenc/use_cases.md
This MR:
- Add a page to the documentation to outline the reasearch project involvement of the CML
- Add a short description of the ALP use case
- Reformats the Use Case page to have one sentence per line - makes it easier to work with in git later.
=> Add research project involvment of CML

docs/agenc/kalp.md
This MR:
- Add a small text about the involvement of KALP
=> Add project involvement text for kalp

docs/examples/one_tank.md
This PR:
- Update the docu for the one tank example to reflect the changes made to the OdeEnvironment
=> Update one tank docu

docs/examples/coffee_machine.md, docs/examples/failure_time_prediction.md, docs/examples/one_tank.md, docs/user_guide/environment.md, docs/user_guide/evaluation.md, docs/user_guide/experiment.md, docs/user_guide/learning_strategies.md, docs/user_guide/modules.md, docs/user_guide/tools.md
- minor updates User Guide
- remove outdated description Coffee Machine
- replace outdated description Failure Time Prediction
- minor corrections One Tank
=> Docu Update

src/flowcean/transforms/__init__.py, src/flowcean/transforms/flatten.py, src/flowcean/utils/__init__.py, src/flowcean/utils/is_time_series.py, tests/transforms/test_flatten.py
This PR:
- Adds a new transform to flatten time series from the "new" format in a polars way.
Closes #41.
=> Add Time series flatten transform

tests/core/test_stack.py
This PR:
- Fixes a bad test class name that was not changed after copy'n'paste.
=> Fix bad test class name

pyproject.toml
Updates metadata in the `pyproject.toml`
=> update sources and issues links in `pyproject.toml`

examples/automatic_lashing_platform/data.dvc
This PR:
- Update the `.json` part of the ALP data to be loadable with a `JsonDataLoader`
~~As it still takes some time to push the data via WebDav, it will probably not be fully available until the beginning of next week.~~
=> Update ALP data

pyproject.toml, src/flowcean/core/environment/incremental.py
Adds a progress bar to the collecting of an incremental environment.
=> tqdm progress bar in env.collect()

src/flowcean/transforms/sliding_window.py, tests/transforms/test_sliding_window.py
This rewrites the sliding window implementation in favor of a much shorter expression.
=> Shorter formulation of sliding window

examples/automatic_lashing_platform/data.dvc
This PR:
- Updates the ALP data - again - and replace the vector valued `valveState` by four scalar features.
=> Update ALP data valve states

src/flowcean/utils/build_environments_from_directory.py
This PR:
- Adds a progressbar to the directory loading.
- Add `tqdm` as an explicit dependency.
Depends on #110. Closes #125.
=> Add progressbar to directory loading

pyproject.toml
Add some classifiers, and exclude data-heavy stuff from the source distribution.
=> Adjust pyproject.toml for publishing

src/flowcean/transforms/__init__.py, src/flowcean/transforms/rename.py, tests/transforms/test_rename.py
This PR:
- Adds a `Rename` transform to change feature names.
=> Add Rename transform

src/flowcean/transforms/__init__.py, src/flowcean/transforms/cast.py, tests/transforms/test_cast.py
This PR:
- Add a new transform to cast features into different data types.
Closes #176.
=> Add Cast transform

src/flowcean/transforms/__init__.py, src/flowcean/transforms/function.py, tests/transforms/test_lambda.py
This PR:
- Adds a `Lambda` transform to apply arbitrary functions to data while conforming to the `Transform` interface and workflow. The file is named `function.py` as `lambda.py` is a restricted name.
=> Add Lambda transform

src/flowcean/transforms/__init__.py, src/flowcean/transforms/drop.py, tests/transforms/test_drop.py
This PR:
- Adds a `Drop` transform to remove features from data.
=> Add Drop transform

src/flowcean/transforms/__init__.py, src/flowcean/transforms/one_cold.py, tests/transforms/test_one_cold.py
This PR:
- Adds a `OneCold` transform.
=> Add One-Cold transform

src/flowcean/transforms/filter.py, tests/transforms/test_filter.py
=> Fix lazy frame usage in filter

justfile
This PR:
- Enable Powershell in just
=> Enable just for windows

examples/ros_offline/run.py, src/flowcean/transforms/__init__.py, src/flowcean/transforms/match_sampling_rate.py, tests/transforms/test_match_sampling_rate.py
=> Match sampling rate reloaded

pyproject.toml, uv.lock
Bump version to `0.4.0` after releasing `0.3.0`
=> bump version to 0.4.0

examples/automatic_lashing_platform/preload_alp_data.py, src/flowcean/core/data.py, src/flowcean/core/environment/active.py, src/flowcean/core/environment/chained.py, src/flowcean/core/environment/incremental.py, src/flowcean/core/environment/join.py, src/flowcean/core/environment/observable.py, src/flowcean/core/environment/offline.py, src/flowcean/core/learner.py, src/flowcean/core/metric.py, src/flowcean/core/model.py, src/flowcean/core/transform.py, src/flowcean/environments/datasetprediction.py, src/flowcean/environments/streaming.py, src/flowcean/metrics/report.py, tests/core/test_joined.py
Annotate all core methods with `Data` which in turn is just an alias for `Any`
Based on #199
=> Data can be Any-thing

docs/examples/robot_localization_failure.md
=> Fix a typo in the README

src/flowcean/polars/transforms/__init__.py, src/flowcean/polars/transforms/first.py, src/flowcean/polars/transforms/last.py, tests/polars/transforms/test_first.py, tests/polars/transforms/test_last.py
This PR:
- Adds a `First` transform to get the first value of a time series feature.
- Adds a `Last` transform to get the last value of a time series feature.
Both transforms offer another way (beside `Flatten` and `Explode`) to convert time series back to "normal" data.
=> First and Last transform for time series data

src/flowcean/polars/transforms/__init__.py, src/flowcean/polars/transforms/mean.py, tests/polars/transforms/test_mean.py
This PR:
- Adds a new `Mean` transform to find the mean value of a time series feature. A new feature with the name `<name>_mean` is added to the dataframe.
=> Mean transform for time series data

src/flowcean/polars/time_series_type.py, src/flowcean/polars/transforms/__init__.py, src/flowcean/polars/transforms/mode.py, tests/polars/transforms/test_mode.py
This PR:
- Adds a `Mode` transform to extract the most frequent element from a time series.
- Adds a new helper script to get the value type of a time series feature.
=> Mode transform for time series data

src/flowcean/polars/__init__.py, src/flowcean/polars/transforms/__init__.py, src/flowcean/polars/transforms/match_sampling_rate.py, tests/polars/transforms/test_match_sampling_rate.py
=> 241 matchsamplingrate transform sometimes returns different length of time series features

src/flowcean/polars/__init__.py, src/flowcean/polars/transforms/__init__.py, src/flowcean/polars/transforms/unnest.py, tests/polars/transforms/test_unnest.py
Adds an unnest transform based on the polars' `unnest` function. The transform can, e.g., be used to unnest time series data.
=> Add unnest transform

examples/active_learning/pyproject.toml, examples/automatic_lashing_platform/pyproject.toml, examples/boiler/pyproject.toml, examples/coffee_machine/pyproject.toml, examples/failure_time_prediction/pyproject.toml, examples/linear_data/pyproject.toml, examples/one_tank/pyproject.toml, examples/robot_localization_failure/pyproject.toml, pyproject.toml
This PR adds a pyright section to every project in our workspace to inherit pyright config.
Additionally it sets the type checking mode to `standard`
=> inherit workspace config for pyright

src/flowcean/core/adapter/__init__.py, src/flowcean/core/adapter/adapter.py, src/flowcean/core/tool/predict.py, src/flowcean/polars/adapter/dataframe_adapter.py
This PR:
- Adds a new `Adapter` class providing an interface to connect CPS with Flowcean in Real-Time.
- Adds a prediction tool loop, to run a `Model` with an `Adapter` in a closed loop.
Closes #257.
=> Add Prediction Tool

examples/robot_localization_failure/custom_transforms/kl_divergence.py
=> Add KL divergence transform

src/flowcean/polars/transforms/__init__.py, src/flowcean/polars/transforms/scale_to_range.py, tests/polars/transforms/test_scale_to_range.py
This PR:
- Adds a `ScaleToRange` transform to linear map features into a defined range. Usefull for deep-learning.
=> Add Scale to Range Transform

src/flowcean/core/environment/offline.py, src/flowcean/polars/environments/dataframe.py, src/flowcean/polars/environments/join.py, tests/polars/test_dataset.py
This PR:
- Adds a `hash` method to `OfflineEnvironments` to detect changes to the environment / it's data.
This approach currently *only* works for `OfflineEnvironments` based around a `polars.DataFrame / LazFrame`. Support for other types of environments would be great but is outside the scope of this PR.
=> Add Environment hashing

docs/getting_started/prerequisites.md
Added a few hints for Windows and Windows with WSL. The other PR #17  can be closed when this is merged.
=> Added windows WSL to prerequisites for getting started

examples/one_tank/run.py, src/flowcean/torch/lightning_learner.py
This PR:
- Adds early stopping to the lightning learner.
- Adds logging of training loss to lightning learner.
Closes #289, Closes #290.
=> Add Early Stopping to Lightning Learner

examples/energy_system/run_with_sac.py, examples/energy_system/run_without_training.py, src/flowcean/core/strategies/active.py, src/flowcean/mosaik/simulator.py, src/flowcean/palaestrai/sac_learner.py, src/flowcean/palaestrai/sac_model.py, src/flowcean/palaestrai/util.py
This implements saving and loading for active learner. To maintain compatibility to palaestrAI models, the learner itself got save/load functions. The model can be saved and loaded individually.
=> Save and load active learner

src/flowcean/polars/__init__.py, src/flowcean/polars/time_series_type.py, src/flowcean/polars/transforms/__init__.py, src/flowcean/polars/transforms/mode.py, src/flowcean/polars/transforms/pad.py, tests/polars/transforms/test_pad.py
This PR
- Adds a `Pad` transform to pad time-series features to a given length by applying a zoh.
=> Pad Timeseries Transform

.github/workflows/ci.yml
=> Update UV  and Just to Latest Versions in CI/CD

docs/examples/xor.md, mkdocs.yml, uv.lock
=> Add XOR Example Documentation
